name: Daily AI Recipe
on:
  schedule:
    - cron: '5 0 * * *' # run daily at 00:05 UTC
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install deps
        run: pip install requests markdown google-cloud-firestore google-auth
      - name: Run daily recipe script
        env:
          HF_API_TOKEN: ${{ secrets.HF_API_TOKEN }}
          GCP_SA_JSON: ${{ secrets.GCP_SA_JSON }} # base64 encoded
          LIST_PATH: untitled://untitled/list.txt
        run: python untitled://untitled/server/daily_recipe.py
